### PR TITLE
Closes #5 - Add main section to index.html

### LINKED ISSUE #5: Add main section to index.html

### PR DESCRIPTION
**Pull request by IhorSolovii**

### CODE REVIEW

**Review by RamzesUAA — APPROVED** [review]
Awesome.

**Review by strelovidniy — APPROVED** [review]

**Review by anastasiiakolomyi — COMMENTED** [review]
good

**Review by anastasiiakolomyi — APPROVED** [review]
good

**Review by strelovidniy — APPROVED** [review]

**Review by r-kovalch — APPROVED** [review]
good

**Pull request merged**
