### PR TITLE
Closes #5 - Add products.json

### LINKED ISSUE #5: Add main section to index.html

### PR DESCRIPTION
**Pull request by IhorSolovii**

### CODE REVIEW

**Review by anastasiiakolomyi — APPROVED** [review]
good

**Review by strelovidniy — APPROVED** [review]
Great job!

**Review by anastasiiakolomyi — APPROVED** [review]
good

**Review by r-kovalch — APPROVED** [review]
good

**Review by RamzesUAA — APPROVED** [review]

**Pull request merged**
