### PR TITLE
Closes #4 - Set title in index.html

### LINKED ISSUE #4: Set title in index.html

### PR DESCRIPTION
**Pull request by RamzesUAA**

### CODE REVIEW

**Review by strelovidniy — APPROVED** [review]

**Review by anastasiiakolomyi — APPROVED** [review]
good

**Review by IhorSolovii — APPROVED** [review]

**Review by anastasiiakolomyi — APPROVED** [review]
good

**Review by IhorSolovii — APPROVED** [review]

**Review by anastasiiakolomyi — APPROVED** [review]
good

**Review by strelovidniy — APPROVED** [review]

**Review by r-kovalch — APPROVED** [review]
пщщв

**Pull request merged**
